export const Theme = {
  polygon: {
    edge: '#555',
    edgeWidth: 0.5,
    vertex: '#000',
    vertexRadius: 4,
    vertex0: 'blue',
    vertex0Width: 1,
    arrowFill: '#bbb',
    arrowHead: 6,
  },
  disc: {
    fill: '#fff',
    highlight: '#e8ffe8',
    border: '#e0e0e0',
    borderWidth: 1,
    inner: '#c6c6c6',
    innerWidth: 1,
    edgeColor: '#555',
    edgeWidth: 0.5,
    vertexColor: '#000',
    vertexRadius: 3,
    vertex0: 'blue',
    vertex0Width: 0.75,
    arrowFill: '#bbb',
    arrowHead: 5,
  },
  averaging: {
    stroke: 'blue',
    lineWidth: 0.75,
  },
  ring: { fill: '#f0f0f0' },
  label: { color: '#777' },
} as const;
